tables:
    products:
        inputs:
            aisles: /opt/airflow/data/bronze/aisles
            departments: /opt/airflow/data/bronze/departments
            products: /opt/airflow/data/bronze/products
        combine: join
        joins:
            -   left: products
                right: aisles
                join_on: aisle_id
                how: left
            -   left: products
                right: departments
                join_on: department_id
                how: left
        output: /opt/airflow/data/silver/dim_products
    orders:
        inputs:
            -   /opt/airflow/data/bronze/orders
        combine: single
        output: /opt/airflow/data/silver/dim_orders
        fillna:
            days_since_prior_order: 0
    order_product:
        inputs:
            -   /opt/airflow/data/bronze/order_products__prior
            -   /opt/airflow/data/bronze/order_products__train
        combine: union
        output: /opt/airflow/data/silver/fact_order_product
bucket: "instacart-platform"
gcs_prefix: "silver"